[project]
name = "tradegrid-commodity-exchange"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.tradegrid-commodity]
path = "contracts/tradegrid-commodity.clar"
depends_on = []

[contracts.tradegrid-reputation]
path = "contracts/tradegrid-reputation.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
